app/__init__.py
import configparser
from os import environ, path


class FILENAMES():
    AKTIVE_HTML = 'aktive_template.html.j2'
    AKTIVE_CSS = 'aktive_template.css'
    REISE_HTML = 'reise_template.html.j2'
    REISE_CSS = 'reise_template.css'

class PATHS():
    ROOT = path.normpath(path.join(path.dirname(__file__), '..'))
    PDF_TEMPLATE_FOLDER = path.join(ROOT,'templates/documents/')
    CONFIG_FILE = path.join(ROOT,'CONFIG.ini')


def _fetch_version() -> str:
    return environ.get('DOCKER_IMAGE_VERSION', '')

def _fetch_config(path:str) -> configparser.ConfigParser:
    config = configparser.ConfigParser()
    with open(path) as f:
        config.read_file(f)
    return config

def _read_contacts(config:configparser.ConfigParser) -> dict[str,str]:
    KEYS = {'Name':'NameVollständig','NameShort':'NameAbgekürzt',
            'LineOne':'AdresseZeile1','LineTwo':'AdresseZeile2',
            'LineThree':'AdresseZeile3','PostCode':'Postleitzahl',
            'City':'Stadt','State':'Bundesland','Country':'Ländercode',
            'Phone':'Telefonnummer','Mail':'EMailAdresse','IBAN':'KontoIBAN',
            'AccName':'KontoName','BIC':'KontoBIC','VAT':'KontoVAT',
            'WebLegal':'WebImpressum','WebPrivacy':'WebDatenschutz',
            'MailAccounting': 'EMailBuchhaltung'}
    out = {}
    for key in KEYS.keys():
        out[key] = config['Kontaktdaten'][KEYS[key]]\
            if config.has_option('Kontaktdaten',KEYS[key]) else ''
    return out

def _read_reise_rate(config:configparser.ConfigParser) -> dict[str,str]:
    KEYS1 = {'GanzerTag':'TagessatzGanz','AnAbreise':'TagessatzReduziert',
             'Einzeltag':'TagessatzEinzeltag'}
    KEYS2 = {'PKWproKM':'FahrtgeldProKM','PKWMaximum':'FahrtgeldMaximum',
             'UebernachtMin':'Übernachtungspauschale'}
    out = {'Tagessatz':{}}
    for key in KEYS1.keys():
        out['Tagessatz'][key] = config['Reisepauschalen'][KEYS1[key]]\
            if config.has_option('Reisepauschalen',KEYS1[key]) else ''
    for key in KEYS2.keys():
        out[key] = config['Reisepauschalen'][KEYS2[key]]\
            if config.has_option('Reisepauschalen',KEYS2[key]) else ''
    return out


#: Die Versionsnummer dieser App.
VERSION = _fetch_version()

config = _fetch_config(PATHS.CONFIG_FILE)
#: Die Kontaktdaten des Vereins.
CONTACT = _read_contacts(config)
#: Die Geldsätze für Reisekostenabrechnungen.
REISE_RATE = _read_reise_rate(config)

app/routes.py
"""
Modul, welches die URL-Pfade für die Flask-App definiert und die
entsprechenden Inhalte anzeigt.
"""

# Imports
from io import BytesIO

from drafthorse.pdf import attach_xml
from flask import Blueprint, render_template, request, abort, send_file
from weasyprint import HTML

from . import aktive, reise, PATHS, CONTACT, REISE_RATE, VERSION

# Constants
STATIC = 'pages.static'

# Routes
pages = Blueprint('pages',__name__,
                  template_folder='templates',
                  static_folder='../static',
                  static_url_path='/static')

@pages.route('/index')
@pages.route('/')
def index():
    """
    Zeigt das Formular zur Erstellung einer Aktivenabrechnung an
    """
    return render_template('form_aktive.html.j2', static=STATIC, version=VERSION,
                           address=CONTACT, abrechnung=aktive.Abrechnung)

@pages.route('/reisekosten')
def reise_form():
    """
    Zeigt das Formular zur Erstellung einer Reisekostenabrechnung an
    """
    return render_template('form_reise.html.j2', static=STATIC, version=VERSION,
                           address=CONTACT, rates=REISE_RATE,
                           abrechnung=reise.Abrechnung)

@pages.route('/abrechnung', methods=['GET'])
def aktive_pdf():
    """
    Zeigt eine Aktivenabrechnung als PDF-Datei an.

    Daten werden aus einem GET-Querystring ausgelesen. Falls es keinen
    gibt, wird ein vorgefertigtes leeres PDF-Dokument angezeigt.
    """
    if request.method == 'GET' and request.args:
        # Query provided; create new PDF
        abrechnung = aktive.Abrechnung()
        # Get data from query string
        errormessage = abrechnung.evaluate_query(request.args.to_dict())
        if errormessage:
            abort(400, errormessage)
        # Prepare electronic invoice as XML
        xml = abrechnung.factur_x()
        # Prepare document as HTML
        document = abrechnung.html_compose()
        # Select a filename for the resulting file
        filename = abrechnung.suggest_filename()+'.pdf'
        # Create PDF from HTML document
        html = HTML(string=document,base_url=PATHS.PDF_TEMPLATE_FOLDER)
        pdf = html.write_pdf()
        # Attach electronic invoice
        pdf = attach_xml(pdf, xml)
        # Return file
        return send_file(BytesIO(pdf), mimetype='application/pdf',
                         as_attachment=True, download_name=filename)
    else:
        # No query provided; use premade empty PDF instead
        return pages.send_static_file('blank/Aktivenabrechnung.pdf')

@pages.route('/reisekosten/abrechnung', methods=['GET'])
def reise_pdf():
    """
    Zeigt eine Reisekostenabrechnung als PDF-Datei an.

    Daten werden aus einem GET-Querystring ausgelesen. Falls es keinen
    gibt, wird ein vorgefertigtes leeres PDF-Dokument angezeigt.
    """
    if request.method == 'GET' and request.args:
        # Query provided; create invoice
        abrechnung = reise.Abrechnung()
        errormessage = abrechnung.evaluate_query(request.args.to_dict())
        if errormessage:
            abort(400, errormessage)
        # Create PDF from invoice
        xml = abrechnung.factur_x()
        document = abrechnung.html_compose()
        filename = abrechnung.suggest_filename()+'.pdf'
        html = HTML(string=document,base_url=PATHS.PDF_TEMPLATE_FOLDER)
        pdf = html.write_pdf()
        pdf = attach_xml(pdf, xml)
        return send_file(BytesIO(pdf), mimetype='application/pdf',
                         as_attachment=True, download_name=filename)
    else:
        # No query provided; use premade empty PDF instead
        return pages.send_static_file('blank/Reisekostenabrechnung.pdf')

@pages.route('/favicon.ico')
def favicon():
    """Returns the favicon."""
    return pages.send_static_file('img/favicon.ico')

templates/form_aktive.html
<!DOCTYPE html>
<html lang="de">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Aktivenabrechnung</title>
	<meta name="description" content="Abrechnungsformular des {{ address['NameShort'] }}" />
	<meta name="author" content="Patrick Lübcke" />
	<meta name="application-name" content="Abrechnungsformular" />
	<meta name="theme-color" content="#004b7c" />
	<link rel="stylesheet" href="{{ url_for(static, filename='css/form.css') }}">
	<link rel="icon" href="{{ url_for(static, filename='img/favicon.ico') }}" sizes="32x32">
	<link rel="icon" href="{{ url_for(static, filename='img/icon.svg') }}" type="image/svg+xml">
	<link rel="apple-touch-icon" href="{{ url_for(static, filename='img/apple-touch-icon.png') }}">
	<link rel="manifest" href="{{ url_for(static, filename='json/manifest.webmanifest') }}">
</head>

<body>
	<header>
		<div>
			<h1>Aktiven&shy;abrechnung</h1>
			<p>Hier findest du das Abrechnungs&shy;formular für Aktive und Helfer&ast;innen beim {{ address['NameShort'] | replace(' ','\xa0') }}.</p>
		</div>
		<nav>
			<!--<a href="#" style="--highlight:red;">Linktext</a>--><a href="{{ url_for('pages.reise_form') }}">Reisekostenabrechnung</a>
		</nav>
	</header>
	<form action="{{ url_for('pages.aktive_pdf') }}" method="get">
		<header>
		<!--Name und Bereich-->
		<fieldset>
			<legend>Persönliche Angaben</legend>
			<section>
				<label class="field">Dein Name: <input type="text" name="uname" id="username" autocomplete="name" required></label>
				<label class="field">Dein Arbeitsbereich: <input type="text" name="dept" id="userdepartment" autocomplete="on" required></label>
			</section>
		</fieldset>
		<!--Projekt--><fieldset class="right">
			<legend>Angaben zur Aktion oder zum Projekt</legend>
			<section>
				<label class="field">Name der Aktion: <input type="text" name="pname" id="projectname" required></label>
				<label class="field">Datum der Aktion: <input type="date" name="pdate" id="projectdate" required></label>
			</section>
		</fieldset>
		</header>
		<!--Geldbeträge-->
		<fieldset>
			<legend>Ausgaben und Einnahmen</legend>
{% for i in range(1,abrechnung.POSITIONCOUNT+1) %}
			<!--Postition {{ i }}-->
			<section id="position{{ i }}section" class="sidebuttons">
				<div class="select">
					<input type="text" class="field" name="p{{ i }}name" id="position{{ i }}name" placeholder="Position {{ i }}" size=24>
				</div>
				<div class="select">
					<label class="option"><input type="radio" id="position{{ i }}minus" name="p{{ i }}type" value=-1 checked>Ausgabe</label>
					<label class="option"><input type="radio" id="position{{ i }}plus" name="p{{ i }}type" value=1>Einnahme</label>
					<!-- <span class="avoidwrap">
						<label class="scriptonly option" hidden><input type="checkbox" id="position{{ i }}multi">Mehrere Stückzahlen</label>
					</span> -->
				</div>
				<div class="subinput">
					<label class="field">Anzahl: <input type="number" name="p{{ i }}cnt" id="position{{ i }}count" min=0 step=1 size=2 value=1></label>
					<label class="field money">Einzelpreis: <input type="number" name="p{{ i }}ppu" id="position{{ i }}price" min="0" step="0.01" class="money"></label>
					<label class="field money">Gesamt: <input type="number" name="p{{ i }}" id="position{{ i }}amount" min="0" step="0.01" class="money"></label>
				</div>
				<input type="button" class="reset jsonly" id="position{{ i }}reset" value="&#9747;" title="Diese Position löschen" hidden>{% if i != 1 %}
				<input type="button" class="up jsonly" id="position{{ i }}up" value="&#8593;" title="Diese Position nach oben verschieben" hidden>{% endif %}{% if i < abrechnung.POSITIONCOUNT %}
				<input type="button" class="down jsonly" id="position{{ i }}down" value="&#8595;" title="Diese Position nach unten verschieben" hidden>{% endif %}
			</section>
{% endfor %}
			<!--Spenden-->
			<section>
					<label class="money">Zusätzlich eingenommene Spenden: <input type="number" name="dono" id="donations" min="0" step="0.01" class="money"></label>
			</section>
		</fieldset>
		<!--Zahlung-->
		<fieldset class="right" id="fieldsetPayment">
			<legend>Zahlungsabwicklung</legend>
			<section id="totalamount">Bitte gib an, wie du diese Abrechnung verbuchen lassen möchtest:</section>
			<!--Überweisung an User-->
			<section>
				<div class="select">
					<label class="option"><input type="radio" id="processtouser" name="prtype" value="1">Wir überweisen den Abrechnungsbetrag auf dein Konto.</label><br>
				</div>
				<div class="subinput">
					<label class="field"><abbr title="Internationale Bankkontonummer">IBAN</abbr>: <input type="text" name="iban" id="processiban" size=22 placeholder="DE12345678901234567890" class="iban"></label>
					<label class="field">Kontoinhaber: <input type="text" name="owner" id="processowner" autocomplete="name"></label>
					<br>
					<label class="option"><input type="checkbox" name="known" id="processuserknown" value="1">Deine Bankverbindung ist dem {{ address['NameShort'] | replace(' ','\xa0') }} bekannt.</label>
				</div>
			</section>
			<!--Einzug-->
			<section>
				<div class="select">
					<label class="option"><input type="radio" id="processsepa" name="prtype" value="2">Den Abrechnungsbetrag per <abbr title="Single Euro Payments Area">SEPA</abbr>-Lastschriftmandat einziehen lassen.</label>
					<aside>Bei Bedarf können wir dir dir das Formular zur Erteilung eines <abbr title="Single Euro Payments Area">SEPA</abbr>-Lastschriftmandats gerne zusenden.</aside>
				</div>
				<div class="subselect">
					<label class="option"><input type="radio" name="prsepa" id="processsepaexists" value="1">Du hast uns bereits ein aktuelles <abbr title="Single Euro Payments Area">SEPA</abbr>-Mandat erteilt.</label>
					<br>
					<label class="option"><input type="radio" name="prsepa" id="processsepanew" value="2">Du hast uns noch kein <abbr title="Single Euro Payments Area">SEPA</abbr>-Mandat erteilt.</label>
					<label class="option"><input type="radio" name="prsepa" id="processsepachange" value="3">Deine Bankverbindung hat sich geändert.</label>
					</div>
			</section>
			<!--Überweisung von User-->
			<section>
				<div class="select">
					<label class="option"><input type="radio" id="processbyuser" name="prtype" value="3">Du überweist den Abrechnungsbetrag selbst.</label>
					<aside id="processnote">Bitte überweise den Abrechnungsbetrag innerhalb von 10 Tagen auf das Konto des {{ address['NameShort'] | replace(' ','\xa0') }} mit der folgenden <abbr title="Internationale Bankkontonummer">IBAN</abbr>: <span class="iban">{{ address['IBAN'] | replace(' ','\xa0') }}</span></aside>
				</div>
			</section>
		</fieldset>
		<!--Absenden-->
		<fieldset class="right">
			<legend>Daten absenden</legend>
			<section class="menu">
				<input type="submit" id="submit" value="Abrechnung erstellen">
				<a href="{{ url_for('pages.aktive_pdf') }}" class="button" draggable=false download="Aktivenabrechnung.pdf">Leere Abrechnung herunterladen</a>
				<input type="reset" id="reset" value="Formular zurücksetzen">
				<aside>Hier kannst du das ausgefüllte Formular als PDF&#8209;Datei herunter&shy;laden und diese dann einfach per E&#8209;Mail an <a href="mailto:{{ address['MailAccounting'] }}">{{ address['MailAccounting'] }}</a> schicken.<br />
				Vergiss dabei nicht, <b>sämtliche Belege</b> an die E&#8209;Mail anzuhängen. Kassen&shy;bons oder andere Papier&shy;belege schickst du als Scan oder notfalls als Foto ein, auf dem <b>der ganze Beleg gut lesbar</b> zu sehen ist.<br />
				Wenn eine Digitalisierung der Belege nicht möglich ist, sende die Abrechnung bitte dennoch per E&#8209;Mail ein. Sende die Belege <b>im Original</b> mit der jeweiligen Positions&shy;nummer versehen, zusammen mit einer Notiz zum Datum der Abrechnung, an unsere Geschäfts&shy;stelle <address>({{ address["NameShort"] }}, {{ address["LineOne"] }}, {% if address["LineTwo"] %}{{ address["LineTwo"] }}, {% endif %}{% if address["LineThree"] %}{{ address["LineThree"] }}, {% endif %}{{ address["PostCode"] }} {{ address["City"] }})</address> oder gib sie dort ab.</aside>
			</section>
		</fieldset>
	</form>
	<footer>
		<nav>
			<a href="{{ address['WebLegal'] }}">Impressum</a><a href="{{ address['WebPrivacy'] }}">Datenschutz</a>
		</nav>{% if version %}
		<div class="version">Abrechnungsformular {{version}}</div>{% endif %}
	</footer>
	<script src="{{ url_for(static, filename='js/form_aktive.js') }}"></script>
</body>

</html>

templates/form_aktive.html.j2
<!DOCTYPE html>
<html lang="de">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Aktivenabrechnung</title>
	<meta name="description" content="Abrechnungsformular des {{ address['NameShort'] }}" />
	<meta name="author" content="Patrick Lübcke" />
	<meta name="application-name" content="Abrechnungsformular" />
	<meta name="theme-color" content="#004b7c" />
	<link rel="stylesheet" href="{{ url_for(static, filename='css/form.css') }}">
	<link rel="icon" href="{{ url_for(static, filename='img/favicon.ico') }}" sizes="32x32">
	<link rel="icon" href="{{ url_for(static, filename='img/icon.svg') }}" type="image/svg+xml">
	<link rel="apple-touch-icon" href="{{ url_for(static, filename='img/apple-touch-icon.png') }}">
	<link rel="manifest" href="{{ url_for(static, filename='json/manifest.webmanifest') }}">
</head>

<body>
	<header>
		<div>
			<h1>Aktiven&shy;abrechnung</h1>
			<p>Hier findest du das Abrechnungs&shy;formular für Aktive und Helfer&ast;innen beim {{ address['NameShort'] | replace(' ','\xa0') }}.</p>
		</div>
		<nav>
			<!--<a href="#" style="--highlight:red;">Linktext</a>--><a href="{{ url_for('pages.reise_form') }}">Reisekostenabrechnung</a>
		</nav>
	</header>
	<form action="{{ url_for('pages.aktive_pdf') }}" method="get">
		<header>
		<!--Name und Bereich-->
		<fieldset>
			<legend>Persönliche Angaben</legend>
			<section>
				<label class="field">Dein Name: <input type="text" name="uname" id="username" autocomplete="name" required></label>
				<label class="field">Dein Arbeitsbereich: <input type="text" name="dept" id="userdepartment" autocomplete="on" required></label>
			</section>
		</fieldset>
		<!--Projekt--><fieldset class="right">
			<legend>Angaben zur Aktion oder zum Projekt</legend>
			<section>
				<label class="field">Name der Aktion: <input type="text" name="pname" id="projectname" required></label>
				<label class="field">Datum der Aktion: <input type="date" name="pdate" id="projectdate" required></label>
			</section>
		</fieldset>
		</header>
		<!--Geldbeträge-->
		<fieldset>
			<legend>Ausgaben und Einnahmen</legend>
{% for i in range(1,abrechnung.POSITIONCOUNT+1) %}
			<!--Postition {{ i }}-->
			<section id="position{{ i }}section" class="sidebuttons">
				<div class="select">
					<input type="text" class="field" name="p{{ i }}name" id="position{{ i }}name" placeholder="Position {{ i }}" size=24>
				</div>
				<div class="select">
					<label class="option"><input type="radio" id="position{{ i }}minus" name="p{{ i }}type" value=-1 checked>Ausgabe</label>
					<label class="option"><input type="radio" id="position{{ i }}plus" name="p{{ i }}type" value=1>Einnahme</label>
					<!-- <span class="avoidwrap">
						<label class="scriptonly option" hidden><input type="checkbox" id="position{{ i }}multi">Mehrere Stückzahlen</label>
					</span> -->
				</div>
				<div class="subinput">
					<label class="field">Anzahl: <input type="number" name="p{{ i }}cnt" id="position{{ i }}count" min=0 step=1 size=2 value=1></label>
					<label class="field money">Einzelpreis: <input type="number" name="p{{ i }}ppu" id="position{{ i }}price" min="0" step="0.01" class="money"></label>
					<label class="field money">Gesamt: <input type="number" name="p{{ i }}" id="position{{ i }}amount" min="0" step="0.01" class="money"></label>
				</div>
				<input type="button" class="reset jsonly" id="position{{ i }}reset" value="&#9747;" title="Diese Position löschen" hidden>{% if i != 1 %}
				<input type="button" class="up jsonly" id="position{{ i }}up" value="&#8593;" title="Diese Position nach oben verschieben" hidden>{% endif %}{% if i < abrechnung.POSITIONCOUNT %}
				<input type="button" class="down jsonly" id="position{{ i }}down" value="&#8595;" title="Diese Position nach unten verschieben" hidden>{% endif %}
			</section>
{% endfor %}
			<!--Spenden-->
			<section>
					<label class="money">Zusätzlich eingenommene Spenden: <input type="number" name="dono" id="donations" min="0" step="0.01" class="money"></label>
			</section>
		</fieldset>
		<!--Zahlung-->
		<fieldset class="right" id="fieldsetPayment">
			<legend>Zahlungsabwicklung</legend>
			<section id="totalamount">Bitte gib an, wie du diese Abrechnung verbuchen lassen möchtest:</section>
			<!--Überweisung an User-->
			<section>
				<div class="select">
					<label class="option"><input type="radio" id="processtouser" name="prtype" value="1">Wir überweisen den Abrechnungsbetrag auf dein Konto.</label><br>
				</div>
				<div class="subinput">
					<label class="field"><abbr title="Internationale Bankkontonummer">IBAN</abbr>: <input type="text" name="iban" id="processiban" size=22 placeholder="DE12345678901234567890" class="iban"></label>
					<label class="field">Kontoinhaber: <input type="text" name="owner" id="processowner" autocomplete="name"></label>
					<br>
					<label class="option"><input type="checkbox" name="known" id="processuserknown" value="1">Deine Bankverbindung ist dem {{ address['NameShort'] | replace(' ','\xa0') }} bekannt.</label>
				</div>
			</section>
			<!--Einzug-->
			<section>
				<div class="select">
					<label class="option"><input type="radio" id="processsepa" name="prtype" value="2">Den Abrechnungsbetrag per <abbr title="Single Euro Payments Area">SEPA</abbr>-Lastschriftmandat einziehen lassen.</label>
					<aside>Bei Bedarf können wir dir dir das Formular zur Erteilung eines <abbr title="Single Euro Payments Area">SEPA</abbr>-Lastschriftmandats gerne zusenden.</aside>
				</div>
				<div class="subselect">
					<label class="option"><input type="radio" name="prsepa" id="processsepaexists" value="1">Du hast uns bereits ein aktuelles <abbr title="Single Euro Payments Area">SEPA</abbr>-Mandat erteilt.</label>
					<br>
					<label class="option"><input type="radio" name="prsepa" id="processsepanew" value="2">Du hast uns noch kein <abbr title="Single Euro Payments Area">SEPA</abbr>-Mandat erteilt.</label>
					<label class="option"><input type="radio" name="prsepa" id="processsepachange" value="3">Deine Bankverbindung hat sich geändert.</label>
					</div>
			</section>
			<!--Überweisung von User-->
			<section>
				<div class="select">
					<label class="option"><input type="radio" id="processbyuser" name="prtype" value="3">Du überweist den Abrechnungsbetrag selbst.</label>
					<aside id="processnote">Bitte überweise den Abrechnungsbetrag innerhalb von 10 Tagen auf das Konto des {{ address['NameShort'] | replace(' ','\xa0') }} mit der folgenden <abbr title="Internationale Bankkontonummer">IBAN</abbr>: <span class="iban">{{ address['IBAN'] | replace(' ','\xa0') }}</span></aside>
				</div>
			</section>
		</fieldset>
		<!--Absenden-->
		<fieldset class="right">
			<legend>Daten absenden</legend>
			<section class="menu">
				<input type="submit" id="submit" value="Abrechnung erstellen">
				<a href="{{ url_for('pages.aktive_pdf') }}" class="button" draggable=false download="Aktivenabrechnung.pdf">Leere Abrechnung herunterladen</a>
				<input type="reset" id="reset" value="Formular zurücksetzen">
				<aside>Hier kannst du das ausgefüllte Formular als PDF&#8209;Datei herunter&shy;laden und diese dann einfach per E&#8209;Mail an <a href="mailto:{{ address['MailAccounting'] }}">{{ address['MailAccounting'] }}</a> schicken.<br />
				Vergiss dabei nicht, <b>sämtliche Belege</b> an die E&#8209;Mail anzuhängen. Kassen&shy;bons oder andere Papier&shy;belege schickst du als Scan oder notfalls als Foto ein, auf dem <b>der ganze Beleg gut lesbar</b> zu sehen ist.<br />
				Wenn eine Digitalisierung der Belege nicht möglich ist, sende die Abrechnung bitte dennoch per E&#8209;Mail ein. Sende die Belege <b>im Original</b> mit der jeweiligen Positions&shy;nummer versehen, zusammen mit einer Notiz zum Datum der Abrechnung, an unsere Geschäfts&shy;stelle <address>({{ address["NameShort"] }}, {{ address["LineOne"] }}, {% if address["LineTwo"] %}{{ address["LineTwo"] }}, {% endif %}{% if address["LineThree"] %}{{ address["LineThree"] }}, {% endif %}{{ address["PostCode"] }} {{ address["City"] }})</address> oder gib sie dort ab.</aside>
			</section>
		</fieldset>
	</form>
	<footer>
		<nav>
			<a href="{{ address['WebLegal'] }}">Impressum</a><a href="{{ address['WebPrivacy'] }}">Datenschutz</a>
		</nav>{% if version %}
		<div class="version">Abrechnungsformular {{version}}</div>{% endif %}
	</footer>
	<script src="{{ url_for(static, filename='js/form_aktive.js') }}"></script>
</body>

</html>